services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        EXTERNAL_SERVER_API: https://dummyjson.com/
        NEXT_PUBLIC_APP_NAME: web
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      HOSTNAME: 0.0.0.0
      PORT: 3000
      EXTERNAL_SERVER_API: https://dummyjson.com/
      NEXT_PUBLIC_APP_NAME: web
