// Generated by AI, then reviewed by me.

import { test, expect } from '@playwright/test'
import { Product } from '../pages/Product'
import { ProductList } from '../pages/ProductList'

test('home page renders product list heading', async ({ page }) => {
   const productList = new ProductList(page)
   await productList.goto()
   await productList.waitForLoaded()
})

test('user can navigate to a product details page', async ({ page }) => {
   const productList = new ProductList(page)
   await productList.goto()
   await productList.waitForLoaded()

   const firstProductTitle = await productList.getFirstProductTitle()
   await productList.clickFirstProduct()

   await expect(page).toHaveURL(/\/products\/\d+$/)

   const product = new Product(page)
   await product.waitForLoaded(firstProductTitle)
})

test('product details page shows core metadata', async ({ page }) => {
   const productList = new ProductList(page)
   await productList.goto()
   await productList.waitForLoaded()
   await productList.clickFirstProduct()

   const product = new Product(page)
   await product.waitForLoaded()

   await expect(product.description).toBeVisible()
   await expect(product.price).toBeVisible()
   await expect(product.category).toBeVisible()
   await expect(product.updatedAt).toBeVisible()
   await expect(product.image).toBeVisible()
})

test('product list exposes multiple product titles', async ({ page }) => {
   const productList = new ProductList(page)
   await productList.goto()
   await productList.waitForLoaded()

   const firstProductTitle = await productList.getFirstProductTitle()
   const secondProductTitle = await productList.getProductTitle(1)

   expect(firstProductTitle.length).toBeGreaterThan(0)
   expect(secondProductTitle?.length ?? 0).toBeGreaterThan(0)
})

test('user can add a product to cart from details page', async ({ page }) => {
   const productList = new ProductList(page)
   await productList.goto()
   await productList.waitForLoaded()

   const firstProductTitle = await productList.getFirstProductTitle()
   await productList.clickFirstProduct()

   const product = new Product(page)
   await product.waitForLoaded(firstProductTitle)
   await product.clickAddToCart()

   await expect(product.cartCountBadge).toContainText('1')
   await product.openCart()
   await expect(page.getByLabel('Your cart').getByText(firstProductTitle, { exact: true })).toBeVisible()
})
